services:
  spring:
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      OPENAI_SECRET_KEY: ${OPENAI_SECRET_KEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    build:
      context: ./spring_server
      dockerfile: Dockerfile.dev  #dev일 때 dev용 Dockerfile 사용

    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env 
    networks:
      - backend

  fastapi:
    build: ./fastapi_server
    container_name: fastapi-app
    # expose:
    #   - "8000"
    ports:
      - "80:8000"
    networks:
      - backend

networks:
  backend:
