services:
  spring:
    build:
      context: ./spring_server
      dockerfile: Dockerfile.dev  #dev일 때 dev용 Dockerfile 사용

    container_name: spring-app
    ports:
      - "8080:8080"
      
    networks:
      - backend

  fastapi:
    build: ./fastapi_server
    container_name: fastapi-app
    # expose:
    #   - "8000"
    ports:
      - "80:8000"
    networks:
      - backend

networks:
  backend:
