# this is for production !!!!!!!!

server :
  port : 8080

spring:
  import: aws-secretsmanager:prod/spring-db-config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
